{% set version = "3.2.4.post1" %}

package:
  name: scs
  version: {{ version }}

source:
  - url: https://github.com/bodono/scs-python/archive/refs/tags/{{ version }}.tar.gz
    sha256: bb509507d857906eb95d17d5824138e48e7c75d1a692d0aa7256d899c7e703c5
  # include submodule (not in github tarball due to dear-github/dear-github#214)
  - git_url: https://github.com/cvxgrp/scs.git
    git_rev: 9024b8ccc1bba6ee797440fb22354cadb9c81839
    folder: scs_source

build:
  number: 0
  script:
    # Copy Meson args split from pandas feedstock but split on cross-compiling
    # instead of unix/win because Linux aarch64 does not work with the Meson
    # args modification (fails to find blas/lapack)
    #
    # See https://github.com/conda-forge/pandas-feedstock/blob/ea054ffba9cda5f10436e1c7250e62d7ee1aacd1/recipe/meta.yaml#L20-L22
    - {{ PYTHON }} -c "import importlib.machinery; print('Extension suffixes:', importlib.machinery.EXTENSION_SUFFIXES)"
    - echo MESON_ARGS $MESON_ARGS
    - echo MESON_ARGS_REDUCED $MESON_ARGS_REDUCED
    # - {{ PYTHON }} -m pip install . -vv -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [not aarch64 and build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt
    - {{ PYTHON }} -m pip install . -vv
  # Following scipy feedstock (see https://github.com/conda-forge/scipy-feedstock/blob/4fde29215004ce771f5407153e4df438b76afa57/recipe/meta.yaml#L43-L45):
  #
  # pypy on aarch/ppc is un(der)maintained and currently broken, see
  # https://github.com/conda-forge/pypy3.6-feedstock/issues/111
  # skip: true  # [ppc64le and python_impl == "pypy"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - libblas
    - liblapack
    - python  # [python_impl == "pypy"]
    - python =3.11 # [python_impl != "pypy"]
    - meson-python
    - pip
    - numpy =1.23
  run:
    - python  # [python_impl == "pypy"]
    - python =3.11 # [python_impl != "pypy"]
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
  run_constrained:
    # avoid installing incompatible cvxpy
    - cvxpy >1.1.15

test:
  imports:
    - scs
    - _scs_direct
    - _scs_indirect
  requires:
    - pytest
  source_files:
    - test/
  commands:
    - pytest test/ -v  # [not ppc64le]
    # NOTE: test suite is skipped on ppc due to bugs in QEMU code that cause
    # CI to fail, even though the tests should run through on native hardware

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for SCS, which solves convex cone problems
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  dev_url: https://github.com/bodono/scs-python

extra:
  recipe-maintainers:
    - djsutherland
    - mcg1969
    - h-vetinari
