# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "imYevkVzDUQc5nTJ1Yf1E7/xeq2nwc4C/Mqto3vR7tLK9GiH/ALbSAZbZ/2RRCRViG/RvDqzQP1ZnZi2Q8RQHStfw+mwNkHqopAeg7VKGUYmNOnHjKzih4G5NMEAnbPJZzQWYoSUOplnPHAQGm9++peCKIJiJL4zALy2sYMOt6XJkpDNiYPG4Wvi+qe3xZ1zcgWUmIxdJXXzyAJTikjXWbUiRJxMl8WPCmnjuYZyJ3UbQYZtFSasKuof7ATDIxQfEWa9dkIlew8acPzxpPsgVT8kvqoXtlsbEE7U8G02MKXzj7B7QAsse0LbcC8n7e0aKCcRyGGppHd+WZFdoE6Mfnf3h0y1DV+tnIc+31JqW8Du88TT6Jh2i9tBrJqpG+rQrvMTZJVgcKUxNxA399/6JZXPx9jpR/tNDub+3LCvrxmDUk9o/fBORn+v3M7L7GcDT34tvcxvHOF5HN3GjMLNb+gypsbPi/jcT50N2Y1U2FdrZfYVrkhdLkjcdhfIPp/Q6b4BTJzyrUrahODv29OgsNlDHLMYlKVf3K3OmFu/QTu7WvXbTU6WbGBjG20hSgrftYVt2aRw9HO//y7Um8bq9ho8EZHROyZPXFK74JtnBH+Hq6o/2E/P6O+BGNXoM1oz92lIfzjaVz97Ci4Sj9Rk3uXwNvPZXtfGMNZcwkx9rk0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_numpy1.16python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.16python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.16python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_numpy1.18python3.6.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi